# Generated by Django 5.0 on 2023-12-14 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cast',
            name='director',
        ),
        migrations.AddField(
            model_name='cast',
            name='cast',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='casts', to='intern.director'),
        ),
    ]
