# Generated by Django 5.0 on 2023-12-14 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0002_remove_cast_director_cast_cast'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cast',
            old_name='cast',
            new_name='casting',
        ),
    ]
