# Generated by Django 5.0 on 2023-12-14 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0003_rename_cast_cast_casting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cast',
            old_name='casting',
            new_name='director',
        ),
    ]
