# Generated by Django 5.0 on 2023-12-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Electronics', 'Electronics'), ('Clothes', 'Clothes'), ('Grocesery', 'Grocesery')], max_length=50)),
                ('image', models.ImageField(upload_to='product_images/')),
                ('desc', models.TextField(max_length=555)),
            ],
        ),
    ]
